{% extends 'layout.swig' %}

{% block body %}
<article>
    <header>
        <h1>SolfegeJS</h1>
        <h2>The modular framework for NodeJS</h2>
    </header>


    <section>
        <h1>Introduction</h1>
    </section>


    <section>
        <h1>Application</h1>
    </section>


    <section>
        <h1>Bundle</h1>
    </section>


    <section>
        <h1>Workflow</h1>
    </section>


    <section>
        <h1>Examples</h1>
    </section>

</article>
{% endblock %}
